# .streamlit/secrets.toml

[connections.snowflake]
user = "APP_USER"
password = "YourStrongPassword123!" # The password you created in Step 4
account = "IXEJZAL-KE35087"       # Your account identifier from Step 2
warehouse = "COMPUTE_WH"
database = "NUTRITION_DB"
schema = "TRACKER_SCHEMA"
role = "APP_ROLE"